// react/src/components/Register.js
import React from 'react'
import { Link } from 'react-router-dom'
import { Header } from './Header'
import DoLoaddding from '../containers/DoLoadding'

let datas = [
    {id:1, label:"用户名：", type:"text", placeholder:"请输入您的用户名", class:"", name:"username"},
    {id:2, label:"密码：", type:"password", placeholder:"请输入您的密码", class:"mui-input-clear", name:"password"},
    {id:3, label:"确认密码：", type:"password", placeholder:"请您再次输入密码", class:"mui-input-clear", name:"rePassword"}
]
export const Register = (props)=> (
    <React.Fragment>
        <Header headerStyle={{leftIcon:"icon icon-return", titel:"注册", rightContent:"", icon:false}} {...props.history}/>
        <form className="mui-input-group" style={{marginTop:"2.5rem"}}>
            {datas.map(
                item=> (
                    <div className={item.class} key={item.id}>
                        <label>{item.label}</label>
                        <input type={item.type} placeholder={item.placeholder} name={item.name} value={props[item.name]} onChange={(ev)=> props.updataInput(ev.target.name, ev.target.value)}/>
                    </div>
                )
            )}
            <div className="mui-button-row" style={{paddingTop:"20px", paddingBottom:"10px", height:"auto"}}>
                <a type="button" className="mui-btn mui-btn-primary" href="javascript:;" style={{width:"90%", padding:"10px 0"}} onClick={()=> props.checkInput(props)}>立即注册</a>
            </div>
            <div style={{paddingBottom:"10px", textAlign:"right", paddingRight:"15px"}}>
                <Link to="/login">已有账号登录</Link>
            </div>
        </form>
        <DoLoaddding/>
    </React.Fragment>
)

// vue/src/components/Register.vue
<template>
    <div>
        <Search/>
        <div class="mui-content">
            <div class="devider b-line"></div>
            <form class="mui-input-group">
                <div class="mui-input-row b-line" v-for="item of userData" :key="item.id">
                    <label v-text="item.label"></label>
                    <input :type="item.type" :class="item.class" :placeholder="item.placeholder" v-model="item.value">
                </div>
                <div class="mui-button-row" :style="item.style" v-for="item of buttonData" :key="item.id">
                    <a :type="item.atype" :class="item.aclass" v-text="item.content" @click="register(item.content)"></a>
                </div>
            </form>
        </div>
    </div>
</template>

<script>
    const Search = ()=> import(/* webpackChunkName: "group-search" */ '@/components/Search')
    import { mapActions } from 'vuex'
    export default {
        name: 'login',
        data() {
            return {
                userData: [
                    {id:1, type:'text', label:'用户名：', placeholder:"请输入您的用户名", class:'', value:''},
                    {id:2, type:'password', label:'密码：',placeholder:"请输入您的密码", class:'mui-input-clear', value:''},
                    {id:3, type:'password', label:'确认密码：',placeholder:"请再次输入您的密码", class:'mui-input-clear', value:''}
                ],
                buttonData: [
                    {id:4, atype:'button', class:'mui-button-row', style:'padding-top:20px; padding-bottom:10px; height:auto', aclass:'mui-btn mui-btn-primary login', content:'注册'},
                    {id:5, atype:'', class:'', style:'padding-bottom:10px; text-align:right; padding-right:15px', aclass:'', content:'已有账号登录'}
                ]
            }
        },
        components: {
            Search
        },
        beforeRouteEnter (to, from, next) {
            next(vm => {
                vm.getBoolean({
                    searchPic: 'mui-icon-arrowleft',
                    chatbubblePic: '',
                    searchContent: '注册'
                })
                vm.changeHref('/home')
            })
        },
        methods: {
            ...mapActions([
                'getBoolean', 'changeHref'
            ]),
            register(content) {
                if(content === '注册') {
                    if(this.userData[0].value === '' || this.userData[1].value === '' || this.userData[2].value === '') alert('Sorry, 用户名和密码不能为空')
                    else if(this.userData[1].value !== this.userData[2].value ) alert('Sorry, 您输入的两次密码不匹配，请重新确认')
                    else{
                        this.axios.defaults.withCredentials = true
                        this.axios.get('http://localhost:9999/login', {
                            params: {
                                doStyle: 'register',
                                username: this.userData[0].value,
                                password: this.userData[2].value
                            }
                        })
                        .then( response=> {
                            if(response.data.register === 'OK') {
                                localStorage.setItem("username", this.userData[0].value);
                                this.$router.push('/home');
                            }
                            else alert('Sorry, 您注册的用户名已存在')
                        })
                        .catch( error=> {
                            console.log(error);
                        })
                    }
                }
                else {
                    this.$router.push('/login')
                }
            }
        }
    }
</script>

<style scoped>
    .login {
        width:90%; 
        padding:10px 0
    }
    .mui-content {
        padding-top: 44px;
    }
</style>
